export const ADD_BOOKMARK = 'ADD_BOOKMARK';
export const REMOVE_BOOKMARK = 'REMOVE_BOOKMARK';
export const VIEW_PLACE_DETAILS = 'VIEW_PLACE_DETAILS';
export const VIEW_BOOKMARK_DETAILS = 'VIEW_BOOKMARK_DETAILS';